[features]
seeds = false
skip-lint = false
[programs.localnet]
transformer = "GTyWp6xRHsSC8QXFYTifGResqVRLt9iGjsifSxNswJtA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
